### ISSUE TITLE
500 error on programme stuff

### ISSUE THREAD

**Issue by katajakasa** [Instanssi/Instanssi.org#37]
Reported by @jpot 

Internal Server Error: /manage/12/programme/
Traceback (most recent call last):
  File "/var/virtualenvs/2015.instanssi.org/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/sites/2013.instanssi.org/common/auth.py", line 18, in _checklogin
    return view_func(request, *args, **kwargs)
  File "/var/sites/2013.instanssi.org/Instanssi/admin_programme/views.py", line 32, in index
    return HttpResponseRedirect(reverse('manage-programme:index', args=(sel_event_id)))
  File "/var/virtualenvs/2015.instanssi.org/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 551, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/var/virtualenvs/2015.instanssi.org/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 468, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'index' with arguments '(u'1', u'2')' and keyword arguments '{}' not found. 1 pattern(s) tried: [u'manage/(?P<sel_event_id>\\d+)/programme/$']

**Comment by katajakasa** [comment]
Resolved in master.
